function ex = initialize_export_options_structure

ex.export = 0;
ex.exportDt = 0;
ex.exportDtMultiplier = 0;
ex.parameters = 0;
ex.vertexStates = 0;
ex.division = 0;
ex.cellStates = 0;
ex.junctions = 0;
ex.cellForcesTotal = 0;
ex.cellForcesArea = 0;
ex.cellForcesCortical = 0;
ex.cellForcesJunctions = 0;
ex.sectionLengths = 0;
ex.areas = 0;
ex.normProperties = 0;
ex.substrate = 0;
ex.exportName = '';